{"name": "Проверка ошибки при повторной регистрации пользователя", "status": "passed", "start": 1727636405818, "stop": 1727636407489, "uuid": "896ae669-9b4d-49b5-8502-13bfd67079f5", "historyId": "808dddae77bcc8d02a827c5e7414e5e2", "testCaseId": "808dddae77bcc8d02a827c5e7414e5e2", "fullName": "tests.test_create_user.TestCreateUser#test_registration_user_twice", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "Notebook"}, {"name": "thread", "value": "26536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}