{"name": "Проверка ошибки при попытке авторизации с некорректным email", "status": "passed", "start": 1727636417257, "stop": 1727636417650, "uuid": "f9afb515-cd4d-4c9f-9c6b-5d9c100e0510", "historyId": "5ca2502ee9c49f4b9bf28e49740790ba", "testCaseId": "5ca2502ee9c49f4b9bf28e49740790ba", "fullName": "tests.test_login_user.TestLoginUser#test_invalid_email_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Notebook"}, {"name": "thread", "value": "26536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}